name: Mateo Torres 
#markdown: redcarpet
highlighter: pygments
description: A place to find rants and some videogame dev stuff!
url: https://torresmateo.com
#url: http://localhost:4000/ 
timezone: "Europe/London"
permalink: /:title/
include: [".well-known"]
